/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#364e00",
        "tertiary": "#ffffff",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#930005",
        "on-primary-fixed": "#131f00",
        "tertiary-container": "#e4e2e1",
        "on-secondary-container": "#ffd2cc",
        "surface-container-high": "#2a2a2a",
        "outline-variant": "#424a33",
        "tertiary-fixed": "#e4e2e1",
        "primary-fixed": "#b2f800",
        "inverse-primary": "#486800",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#9bd900",
        "inverse-on-surface": "#313030",
        "surface-tint": "#9bd900",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474746",
        "on-secondary": "#690003",
        "on-surface-variant": "#c2caad",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "on-primary": "#243600",
        "on-secondary-fixed": "#410001",
        "outline": "#8c9479",
        "on-tertiary": "#303030",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container": "#201f1f",
        "on-tertiary-container": "#656464",
        "primary-container": "#b2f800",
        "primary": "#ffffff",
        "on-tertiary-fixed": "#1b1c1c",
        "surface": "#131313",
        "secondary-fixed-dim": "#ffb4aa",
        "secondary-fixed": "#ffdad5",
        "on-primary-container": "#4d6e00",
        "surface-container-highest": "#353534",
        "secondary": "#ffb4aa",
        "background": "#131313",
        "secondary-container": "#c5020b",
        "on-error": "#690005",
        "surface-container-low": "#1c1b1b",
        "on-surface": "#e5e2e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "0px",
        "gutter-mobile": "0px",
        "space-md": "12px",
        "space-sm": "8px",
        "margin-mobile": "0px",
        "space-xs": "4px",
        margin: "0px",
        "space-lg": "16px",
        "space-xl": "24px",
      },
      fontFamily: {
        "body-sm": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "headline-sm": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "body-md": ["JetBrains Mono"],
        "headline-xl": ["Space Grotesk"],
        "headline-xl-mobile": ["Space Grotesk"],
        "body-lg": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
        "code-dense": ["JetBrains Mono"],
      },
      fontSize: {
        "body-sm": ["11px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-sm": ["14px", { lineHeight: "18px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["20px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "36px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-xl-mobile": ["24px", { lineHeight: "28px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "500" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "code-dense": ["10px", { lineHeight: "14px", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
